---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: nginx
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:    
    metadata:
      labels:
        run: nginx      
    spec:       
      containers:
        - image: nginx
          name: nginx          
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.25"
            limits:
              memory: "512Mi"
              cpu: "0.50"


