
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config1
  labels:
    app: postgres1
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  
---
  apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres1
  template:   
    metadata:
      labels:
        app: postgres1
    spec:      
        containers:
          - name: postgres1
            image: postgres:10.4
            ports:
              - containerPort: 5432
            envFrom:
              - configMapRef:
                  name: postgres-config1      
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1024Mi"
                cpu: "500m"
---   
apiVersion: v1
kind: Service
metadata:
  name: postgres1
  labels:
    app: postgres1
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres1
                
